country=CN
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
	ssid="pcTeacher"
	psk="88888888"
	priority=100
}
network={
	ssid="pcStudent"
	psk="88888888"
	priority=99
}
network={
	ssid="pcLisi"
	psk="88888888"
	priority=98
}
